# Generated by Django 4.0.6 on 2022-07-28 04:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('MA_login', '0003_alter_dailyactivitypost_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyactivitypost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 28, 4, 48, 3, 246821, tzinfo=utc)),
        ),
    ]
