# Generated by Django 4.0.6 on 2022-07-28 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MA_login', '0006_alter_dailyactivitypost_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyactivitypost',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyactivitypost',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
