# Generated by Django 4.0.6 on 2022-07-27 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyactivitypost',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
