# Generated by Django 4.0.6 on 2022-07-28 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_dailyactivitypost_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyactivitypost',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
