# Generated by Django 4.0.6 on 2022-08-02 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_dailyactivitypost_description'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dailyactivitypost',
            table='dailyActivityPost',
        ),
    ]
