# Generated by Django 4.0.6 on 2022-08-02 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_dailyactivitypost_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyactivitypost',
            name='created',
            field=models.DateTimeField(null=True),
        ),
    ]
