# Generated by Django 4.0.6 on 2022-08-02 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_dailyactivitypost_created'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dailyactivitypost',
            table=None,
        ),
    ]
