# Generated by Django 4.0.6 on 2022-08-02 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_rename_dailyactivitypost_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created',
        ),
    ]
