# Generated by Django 4.0.6 on 2022-08-02 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_rename_post_dailyreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('techName', models.TextField(max_length=75, null=True)),
                ('location', models.TextField(max_length=50, null=True)),
                ('serialNumber', models.TextField(max_length=50, null=True)),
                ('make', models.TextField(max_length=50, null=True)),
                ('model', models.TextField(max_length=50, null=True)),
                ('gameName', models.TextField(max_length=75, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('category', models.TextField()),
                ('description', models.TextField(max_length=500, null=True)),
                ('notes', models.TextField(max_length=1500, null=True)),
                ('solution', models.TextField(max_length=1500, null=True)),
            ],
        ),
    ]
