# Generated by Django 4.0.6 on 2022-08-03 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_incident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='incident',
            name='gameName',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='make',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='model',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='serialNumber',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='techName',
            field=models.CharField(max_length=75, null=True),
        ),
    ]
