# Generated by Django 4.0.6 on 2022-08-05 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_incident_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incident',
            old_name='description',
            new_name='incident',
        ),
    ]
