# Generated by Django 4.0.6 on 2022-08-05 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_incident_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='notes',
        ),
    ]
