# Generated by Django 4.0.6 on 2022-08-13 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_dailyreport_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
