# Generated by Django 4.0.6 on 2022-08-14 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_dailyreport_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
