# Generated by Django 4.0.6 on 2022-08-15 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_dailyreport_created_alter_incident_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='category',
            field=models.CharField(choices=[('TG', 'Table Games'), ('CG', 'Cage'), ('RC', 'Recycler'), ('OT', 'Off Track Betting'), ('BE', 'Bench')], default='SM', max_length=2),
        ),
    ]
