# Generated by Django 4.0.6 on 2022-08-15 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_incident_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='category',
            field=models.CharField(choices=[('TG', 'Table Games'), ('CG', 'Cage'), ('RC', 'Recycler'), ('OT', 'Off Track Betting'), ('BE', 'Bench'), ('SM', 'Slot Machines'), ('MC', 'Misc')], default='SM', max_length=2),
        ),
    ]
