# Generated by Django 4.0.6 on 2022-08-15 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_alter_incident_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='category',
            field=models.CharField(choices=[('Slot Machines', 'Slot Machines'), ('Table Games', 'Table Games'), ('Cage', 'Cage'), ('Recycler', 'Recycler'), ('Off Track Betting', 'Off Track Betting'), ('Bench', 'Bench'), ('Vendor', 'Vendor'), ('NRT', 'NRT'), ('Misc', 'Misc')], default='Slot Machines', max_length=20),
        ),
    ]
